#FROM mcr.microsoft.com/azure-sql-edge:latest
FROM mcr.microsoft.com/mssql/server:latest

USER root

RUN apt update && apt install -y curl

WORKDIR /app

COPY . /app

RUN chmod +x *.sh

USER mssql

ENTRYPOINT /bin/bash ./entrypoint-arm64.sh
